name: readthedocs/actions
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths:
      - "docs/**"

jobs:
  permissions:
    pull-requests: write
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "main"